### PR TITLE
Update to Systems and Testing section of the documentation

### PR DESCRIPTION
**Pull request by Akinbola247**
This pull request references issue #57. Changes as regards how tests are written has been made, and systems section now includes events implementation in the sample. i await your review and feedback.

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
Thank you for this!

We have been getting 0.3.0 up to date, and testing has changed slightly. Would you be able to update this feature to 0.3.0 style testing (can be found in head of dojo core) ?

**Comment by Akinbola247** [comment]
Oh yes! i can do that!.

**Comment by ponderingdemocritus** [comment]
make the PR into the 0.3.0 branch please - https://github.com/dojoengine/dojo/tree/main/examples/ecs

**Comment by Akinbola247** [comment]
I've made the PR into 0.3.0 as per request and also updated the feature to 0.3.0

**Comment by ponderingdemocritus** [comment]
this is still merging into main

**Comment by Akinbola247** [comment]
Oh I already made the PR to 0.3.0 branch and it has been merged. Does this imply that the 0.3.0 update does not need to apply to the main branch? if yes, then you can go ahead to close the PR i made to the main branch.

**Pull request closed without merging**
