### PR TITLE
refactor to 4 types of documentation

### PR DESCRIPTION
**Pull request by gogo2464**
Not a great update by itself.

Still a good template in order to product more and more clearer documentation.

### CODE REVIEW

**Comment by gogo2464** [comment]
Not a great update by itself.

Still a good template in order to product more and more clearer documentation.

**Comment by gogo2464** [comment]
The world chapter is not printed yet.

Not ready to merge.

**Comment by tarrencev** [comment]
> Issue fixed. Ready for a review.
> 
> I am still adding more content. We could use another PR as well for the content.

Lets open up additional PR's against this one, then merge into here then to main, so we dont publish empty chapters

**Comment by gogo2464** [comment]
for HOW to and API REF or for old empty chapters that were already empty?

**Comment by gogo2464** [comment]
@tarrencev hello,

I am documenting the concepts. Is there any risk that I accidentally put personnal information on the ethereum blockchain by accident please?

Could you tell the name of the chapter that I need to fill please? I am confused. Sorry for the inconvenience.

**Comment by gogo2464** [comment]
I had almost finish.

@tarrencev After reading my doc once again I realized I got experience and I found tons of issues:

- some explanation must have their equivalent in tutorial. 
- I should document general game engine internal in the chapter number 4. 
- The chapter 4 should not be specifically to dojo engine.
- missing tutorials.
 
Anyway the setup documentation was good.

I had a lack of understanding of the project. I now understand it was a kind of NFT map sharing. I misunderstood that. I used to believed it use the blockchain to share data. IT is true for assets but nothing more.

I also have to say I was struggling in order to understand the dojo internals...

**Comment by tarrencev** [comment]
hey @gogo2464 sorry i thought this issue was stale. would love to consider and integrate your suggestions. do you mind opening smaller PR's and coordinating with @ponderingdemocritus on larger changes to the structure?

**Comment by gogo2464** [comment]
I am a professional dev. I only need review. Not coordinating. Yes I will do it more incrementally. I will start with explanation in order to really see if I understand the software for me. Then I will write tutorials and more.

Thank you for the coordinating purpose anyway. If really required. Let's talk on discord.

**Comment by gogo2464** [comment]
could you reopen please?

**Comment by gogo2464** [comment]
I think my pr is cool but too big for a good first issue.

**Pull request closed without merging**
