### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by LamsyA**
Update documentation to include Rust installation requirement for Dojo

### CODE REVIEW

**Comment by glihm** [comment]
Thanks for this important update. I included a part but perhaps not all in the new version. Could you please rebase and add missing stuff? I think I missed the part of the path.

Thank you a lot. 🙏

**Comment by LamsyA** [comment]
> Thanks for this important update. I included a part but perhaps not all in the new version. Could you please rebase and add missing stuff? I think I missed the part of the path.
> 
> Thank you a lot. 🙏

Done ✅

**Comment by glihm** [comment]
> @glihm This is ready for review.

Could you ensure it's not doubled with the section just below yours which already contains Cargo stuff? A little cleanup and we should be fine. :)

**Comment by LamsyA** [comment]
Hi @glihm,  All clean-up done 
Kindly review it

**Pull request merged**
