### PR TITLE
feat: i18n support for mdbook

### PR DESCRIPTION
**Pull request by dpinones**
This PR adds support for the i18n mdbook extension.

- Added a script translation.sh to facilitate the work.
- The CI has also been modified to use Rust's cache. The CI always builds the English version first and then the translations.
- When modifying a translation, only the po files will be changed. The book's structure remains completely intact.

To create this PR, I based it on the [Beerus Book](https://github.com/keep-starknet-strange/beerus/pull/437) and [Cairo Book](https://github.com/cairo-book/cairo-book.github.io/pull/130).

It's already functional in a test repository:
Repository: https://github.com/dpinones/dojo-book
Actions: https://github.com/dpinones/dojo-book/actions
Book: https://dpinones.github.io/dojo-book/

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
Great contribution! Will you also be doing the full translation?

**Comment by dpinones** [comment]
> Great contribution! Will you also be doing the full translation?

Thanks @ponderingdemocritus!  Yes, I'll finish the translation tomorrow :)

**Comment by dpinones** [comment]
> Great contribution! Will you also be doing the full translation?

Complete translation 😃 Preview here: https://dpinones.github.io/dojo-book/

**Comment by kariy** [comment]
i love this

**Pull request merged**
